=== wcs7777/arranke/backend/src/json-schemas/resources/users/individual-update.schema.json
{
	"$id": "https://arranke.com/resources/users/individual-update.schema.json",
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"title": "Individual Update",
	"type": "object",
	"properties": {
		"name": { "$ref": "../../properties/individuals/name" },
		"email": { "$ref": "../../properties/individuals/email" },
		"phone": { "$ref": "../../properties/individuals/phone" },
		"cpf": { "$ref": "../../properties/individuals/cpf" },
		"address": {
			"type": "object",
			"$ref": "../../properties/individuals/address",
			"required": ["cep", "state", "city", "area", "street", "number"]
		}
	},
	"required": ["name", "email", "phone", "cpf", "address"]
}

=== wcs7777/arranke/backend/json-examples/users/individual-update.json
{
	"name": "Usuário Quatro - Atualizado",
	"email": "usuario4atualizado@email.com",
	"phone": "87558215102",
	"cpf": "81833099095",
	"address": {
		"cep": "06665100",
		"state": "SP",
		"city": "Itapevi",
		"area": "Conjunto Habitacional - Setor A",
		"street": "Rua Macaúba",
		"number": "232"
	}
}
